[package]
name = "twiggy"
version = "0.1.0"
edition = "2021"
authors = ["Twiggy Development Team"]
description = "Lightning-fast Git visualization tool"
license = "MIT OR Apache-2.0"
repository = "https://github.com/twiggy-dev/twiggy"
homepage = "https://twiggy-git.dev"

[dependencies]