[package]
name = "twiggy"
version = "0.1.0"
edition = "2021"
authors = ["Twiggy Development Team"]
description = "Lightning-fast Git visualization tool"
license = "MIT OR Apache-2.0"
repository = "https://github.com/twiggy-dev/twiggy"
homepage = "https://twiggy-git.dev"

[dependencies]
egui = "0.24"
eframe = { version = "0.24", features = ["default_fonts", "glow", "persistence"] }
git2 = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full", "macros", "rt-multi-thread"] }
directories = "5.0"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json", "time", "local-time"] }
tracing-appender = "0.2"
rfd = "0.12"

[dependencies.winapi]
version = "0.3"
features = ["winuser", "psapi", "processthreadsapi"]

[dev-dependencies]
tempfile = "3.8"

[[test]]
name = "error_handling_tests"
path = "tests/error_handling_tests.rs"

[[test]]
name = "config_tests"
path = "tests/config_tests.rs"