[package]
name = "twiggy"
version = "0.1.0"
edition = "2021"
authors = ["Miguel"]
description = "Lightning-fast, minimalist Git visualization tool"

[dependencies]
eframe = "0.29"
egui = "0.29"
git2 = "0.18"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"